
    create table Atributo (
        DTYPE varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        fecha date,
        valor numeric(19,2),
        formula varchar(255),
        expresion_id bigint,
        empresa_id bigint,
        primary key (id)
    )

    create table CondicionGeneral (
        tipoDeCondicion varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        comparador integer,
        periodoDeEvaluacion integer,
        valorContraElQueComparar numeric(19,2),
        funcion_id bigint,
        metodologia_id bigint,
        primary key (id)
    )

    create table empresa (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    create table expresion (
        tipoDeExpresion integer not null,
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        valor numeric(19,2),
        operandoDer_id bigint,
        operandoIzq_id bigint,
        primary key (id)
    )

    create table funciones (
        tipoDeFuncion varchar(31) not null,
        id bigint generated by default as identity (start with 1),
        indicador_id bigint,
        primary key (id)
    )

    create table metodologia (
        id bigint generated by default as identity (start with 1),
        nombre varchar(255),
        primary key (id)
    )

    alter table Atributo 
        add constraint FK_o2hu844n67uk7y49gfj70uhtb 
        foreign key (expresion_id) 
        references expresion

    alter table Atributo 
        add constraint FK_errdpei3ti6kekdmhcbtcpke4 
        foreign key (empresa_id) 
        references empresa

    alter table CondicionGeneral 
        add constraint FK_6a094fxinmwlikut9lv4q8rpn 
        foreign key (funcion_id) 
        references funciones

    alter table CondicionGeneral 
        add constraint FK_pvflvhguda5gw5sn1ujnn8asx 
        foreign key (metodologia_id) 
        references metodologia

    alter table expresion 
        add constraint FK_la5opspiy6el4ya1nqy1leb69 
        foreign key (operandoDer_id) 
        references expresion

    alter table expresion 
        add constraint FK_e3m52ka2ubenjh5qqcugsf12u 
        foreign key (operandoIzq_id) 
        references expresion

    alter table funciones 
        add constraint FK_ckx2v9riarntwohnldoruoy37 
        foreign key (indicador_id) 
        references Atributo
