/* Generated By:JavaCC: Do not edit this line. ParserTPConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserTPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAS = 5;
  /** RegularExpression Id. */
  int MENOS = 6;
  /** RegularExpression Id. */
  int POR = 7;
  /** RegularExpression Id. */
  int DIVIDIDO = 8;
  /** RegularExpression Id. */
  int OPENPAR = 9;
  /** RegularExpression Id. */
  int CLOSEPAR = 10;
  /** RegularExpression Id. */
  int NUMERO = 11;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 12;
  /** RegularExpression Id. */
  int CUENTA = 13;
  /** RegularExpression Id. */
  int LETTER = 14;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "<NUMERO>",
    "<IDENTIFICADOR>",
    "<CUENTA>",
    "<LETTER>",
  };

}
